name: flutter_bloc_architecture_demo
description: Flutter app for demostrating BLoC architecture with TDD...

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  connectivity_plus: ^1.0.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  bloc_test: ^8.0.0

dev_dependencies:

  mocktail: ^0.1.2
  build_runner: ^2.0.3

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

